version: 2.1
jobs:
  install:
    working_directory: ~/meteor
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm --version
            node --version
            npm ci
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/meteor
          paths:
            - node_modules
  unit-test:
    working_directory: ~/meteor
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/meteor
      - run:
          name: Run Tests
          command: npx vitest run
  cypress:
    working_directory: ~/meteor
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Start CI
          command: ssh open-sky.fr "~/env-ci.sh start"
      - run:
          name: Run cypress tests
          command: |
            docker run -it -v ~/meteor:/e2e -w /e2e cypress/included:12.13.0 run --env user=ci@open-sky.fr,password=${USER_METEOR_PASSWORD},urlAuth=https://ci.meteor.open-sky.fr/jsrm/auth/signin --config baseUrl=https://ci.meteor.open-sky.fr,defaultCommandTimeout=8000
      - store_artifacts:
          path: ~/meteor/cypress/videos
      - store_artifacts:
          path: ~/meteor/cypress/screenshots
      - store_artifacts:
          path: ~/meteor/cypress/downloads
      - run:
          name: Stop CI
          command: ssh open-sky.fr "~/env-ci.sh stop"
          when: always
  package-ci:
    working_directory: ~/meteor
    resource_class: large
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/meteor
      - run:
          name: Build for CI
          command: npm run build -- --mode ci
      - run:
          name: zip dist
          command: |
            cd ./dist
            zip -r meteor-dist.zip ./
      - store_artifacts:
          path: meteor-dist.zip
      - persist_to_workspace:
          root: ~/meteor
          paths:
            - dist
            - ansible
  package-prod:
    working_directory: ~/meteor
    resource_class: large
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/meteor
      - run:
          name: Build for CI
          command: npm run build
      - run:
          name: zip dist
          command: |
            cd ./dist
            zip -r meteor-dist.zip ./
      - store_artifacts:
          path: meteor-dist.zip
      - persist_to_workspace:
          root: ~/meteor
          paths:
            - dist
            - ansible
  deploy:
    working_directory: ~/meteor
    docker:
      - image: quay.io/ansible/ansible-runner:stable-2.9-latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: 'false'
    parameters:
      front-folder:
        type: string
        default: "meteor-ci"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:7e:ed:8d:47:13:0a:7e:8e:c4:72:b5:18:75:17:71"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/meteor
      - run: |
          ssh-keyscan -H open-sky.fr >> ~/.ssh/known_hosts
      - run:
          name: Deploy to <<parameters.front-folder>>
          command: |
            cd ~/meteor/ansible
            ansible-playbook -i inventory open-sky.fr.yml --extra-vars frontFolder=<<parameters.front-folder>>
  cypress-check-prod:
    working_directory: ~/meteor
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Run cypress tests
          command: |
            docker run -it -v ~/meteor:/e2e -w /e2e cypress/included:12.13.0 run --env user=ci@open-sky.fr,password=${USER_METEOR_PASSWORD},urlAuth=https://www.meteor.open-sky.fr/jsrm/auth/signin --config baseUrl=https://meteor.open-sky.fr --spec ./cypress/e2e/IT/run-in-SI-units.cy.js
      - store_artifacts:
          path: ~/meteor/cypress/videos
      - store_artifacts:
          path: ~/meteor/cypress/screenshots
workflows:
  version: 2
  check-production:
    triggers:
      - schedule:
          cron: "0 4 * * 0,2,4,6"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress-check-prod
  build-test-and-approval-package:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - unit-test:
          filters:
            tags:
              only: /^v.*/
          requires:
            - install
      - package-ci:
          requires:
            - unit-test
          filters:
            tags:
              ignore: /.*/
      - package-prod:
          requires:
            - unit-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          name: deploy-ci
          requires:
            - package-ci
          filters:
            tags:
              ignore: /.*/
      - cypress:
          requires:
            - deploy-ci
          filters:
            tags:
              ignore: /.*/
      - deploy:
          name: deploy-prod-auto-tag
          front-folder: "meteor"
          requires:
            - package-prod
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
